services:
  yopass:
    image: tassilopitrasch/yopass
    container_name: yopass
    depends_on:
      - yopass_redis
    restart: always
    networks:
      - yopass_internal
      - yopass_external
    ports:
      - "80:80"
    command: "--database=redis --redis=redis://yopass_redis:6379/0 --port 80"

  yopass_redis:
    image: redis
    container_name: yopass_redis
    restart: always
    networks:
      - yopass_internal
    volumes:
      - "yopass_redis_data:/data"
    command: "redis-server"

networks:
  yopass_internal:
    internal: true
  yopass_external:
    driver: bridge
    internal: false

volumes:
  yopass_redis_data:
