services:
  yopass:
    image: TassiloPitrasch/yopass:latest
    container_name: yopass
    restart: always
    networks:
      - yopass_internal
      - yopass_external
    ports:
      - "80:80"
    command: "--database=memcached --memcached=yopass_memcached:11211 --port 80"

  memcached:
    image: memcached:latest
    container_name: yopass_memcached
    restart: always
    networks:
      - yopass_internal

networks:
  yopass_internal:
    internal: true
  yopass_external:
    driver: bridge
    internal: false
